---


- name: create {{ MIRROR_DIR }} directory
  file:
    path: "{{ MIRROR_DIR }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0777
    setype: httpd_sys_content_t



- name: Download mirror
  shell: |
    # lowercase initial s, remove trailing slash if it exists
    DM=$(echo -n {{ DEPLOYMENT_MIRROR }} | sed "s/^S/s/" | sed "s+/$++" )

    EC2_REGION="$(aws s3api get-bucket-location --bucket {{ DEPLOYMENT_DATA_LOCATION.split("/")[0] }} --output text)"
    loc_ret=$?
    if [ "$loc_ret" -ne 0 ]; then
      for region in $(aws ec2 describe-regions --region us-east-1 --output text --query "Regions[].RegionName"); do
      echo "Checking region $region"
      EC2_REGION="$(aws s3api get-bucket-location --bucket {{ DEPLOYMENT_DATA_LOCATION.split("/")[0] }} --output text)"
      loc_ret=$?
      if [ "$loc_ret" -eq 0 ]; then
          break
      fi
      done

    fi
    EC2_REGION="${EC2_REGION/None/us-east-1}"

    aws --region ${EC2_REGION} s3 sync ${DM} /opt/sas/mirror


- name: install httpd
  yum: name=httpd

- name: set httpd port to 8008
  replace:
    dest: /etc/httpd/conf/httpd.conf
    regexp:  'Listen.*'
    replace: 'Listen 8008'

- name: configure httpd
  blockinfile:
    dest: /etc/httpd/conf.d/repo.conf
    create: yes
    marker: '# {mark} sas mirror repo'
    block: |
      <Directory "/opt/sas/mirror/">
        Options All
        AllowOverride All
        Require all granted
        Satisfy any
      </Directory>
      Alias "/repo_mirror" "/opt/sas/mirror/"

- name: start httpd
  service:
    name: httpd
    enabled: yes
    state: started
