---

- hosts: [CASControllerServer]
  become: yes
  become_user: sas

  tasks:
  - name: add ELB/Domain to CAS configuration
    lineinfile:
      dest: /opt/sas/viya/config/etc/cas/default/casconfig_usermods.lua
      line: "env.CAS_VIRTUAL_HOST = '{{cas_virtual_host}}'"
      state: present
    tags:
      - cas

  - name: restart cas controller
    become: yes
    become_user: root
    service:
      name: sas-viya-cascontroller-default
      state: restarted
    tags:
      - cas


- hosts: [shared-vault-server]
  become: yes
  become_user: root

  tasks:
  - name: set up sharedVault
    shell: |
      mkdir -p /opt/sas/backups
      chown sas:sas /opt/sas/backups
      yum -y install nfs-utils
      systemctl start nfs
      systemctl enable nfs
      echo "/opt/sas/backups *(rw,sync)" > /etc/exports
      exportfs -a
      chown sas:sas /opt/sas/backups
    tags:
      - backups

- hosts: sas-all
  become: yes
  become_user: root

  tasks:
  - name: create and mount /backups directory
    shell: |
      mkdir -p /backups
      yum -y install nfs-utils autofs
      echo "/- /etc/auto.backups" > /etc/auto.master
      echo "/backups -rw,soft,uid=$(id sas -u),gid=$(id sas -g) stateful.viya.sas:/opt/sas/backups" > /etc/auto.backups
      systemctl start autofs
      systemctl enable autofs
      chown sas:sas /backups
    tags:
      - backups

